### ISSUE TITLE
Add me as a contributor

### ISSUE THREAD

**Issue by webrgp** [zimmen/gulp-twig#37]
Hi Simmon,

Can you add me as a contributor to this repo? Let me know what do you need from me to make it happen. Thanks!

**Comment by olets** [comment]
Fwiw I've sent him a bunch of notes across various platforms, asking the same thing, with no response in months. Hope he's okay!

**Comment by webrgp** [comment]
Too bad...

**Comment by dotmagic** [comment]
I was asking him some months ago too. Never got a reply :(
How about creating a fork and develop it together in a more open source manner?
I'm thinking about gulp-twigjs

**Comment by zimmen** [comment]
Sorry guys, i'll try to make some time today.

**Comment by bezoerb** [comment]
Also offered some help about 8 months ago with no reply ;)

**Comment by zimmen** [comment]
There, sorry guys, i have added you all as collaborators. As you have probably guessed my time is 120% allocated for other things!

**Comment by zimmen** [comment]
I guess some WOW is in order. To make sure things are in collaberation, I have set up the master branch as a protected branch, requiring at least 1 PR review in order to merge to. Travis is running the builds https://travis-ci.org/zimmen/gulp-twig. 

I don't know who to add to npm as Collaborator, as i do not know your names there.

**Comment by webrgp** [comment]
Thanks @zimmen!

**Comment by olets** [comment]
Thanks @zimmen! I'm on npm now as **olets**

**Comment by dotmagic** [comment]
Thanks, just updated my pull request #34 to twig.js 0.10.5. Maybe it's a good time to prepare a new release? How about 0.7.1?
